### ISSUE TITLE
Injective message encoding/decoding in Ristretto?

### ISSUE THREAD

**Issue by weikengchen** [Ristretto/libristretto255#40]
Hi Ristretto Group,

This issue is a question about **injective message encoding/decoding in Ristretto**.

In some ElGamal implementations, we need to map a message string to a point on a curve, and inversely map it later. To enjoy efficient scalar multiplication, people will prefer curves like Curve25519. To make ElGamal semantically secure, we may choose cofactor-elimination like Decaf and Ristretto. So, it comes to Ristretto, which seems to be the best choice for this quest.

To implement the string-to-point / point-back-to-string mapping, the natural constant-time, provably working approach is the elligator 2. 

That is, we map a string $m$ into a point $P_m$. To inverse $P_m$, we use the inverse elligator, which we get likely 16 preimages $m_1, m_2, ..., m_16$. 

**The challenge:** How to identify the original message $m$ among them?

The walkaround in my mind is to embed a hash at the end of the message so that under the random oracle model, we can distinguish the original message from other preimages with negligible failure. But this seems to be too naive and costly (it reduces the message space by about 80-bit for the hash).

Any thoughts? Thanks!

-----------

_Footnote:_ One strawman walkaround is to use hybrid encryption as the elligator paper suggested, such that we no longer need to encode random messages. Yet, this does not work for some applications where we cannot use an elligator, like implementing public-key re-randomizable encryption for shuffling networks.

**Comment by bitwiseshiftleft** [comment]
Hi Weiking,




Sorry for the slow response.  I'm afraid I don't have a magical solution for you, but you could try adding a small (eg 8-bit) random component and a small (eg 8-bit) checksum. Then when encoding you can retry random components until only the intended message passes the checksum.




-- Mike




Sent from my phone







On Sun, Jan 13, 2019 at 5:07 PM -0800, "Weikeng Chen" <notifications@github.com> wrote:












Hi Ristretto Group,


This issue is a question about injective message encoding/decoding in Ristretto.


In some ElGamal implementations, we need to map a message string to a point on a curve, and inversely map it later. To enjoy efficient scalar multiplication, people will prefer curves like Curve25519. To make ElGamal semantically secure, we may choose cofactor-elimination like Decaf and Ristretto. So, it comes to Ristretto, which seems to be the best choice for this quest.


To implement the string-to-point / point-back-to-string mapping, the natural constant-time, provably working approach is the elligator 2.


That is, we map a string $m$ into a point $P_m$. To inverse $P_m$, we use the inverse elligator, which we get likely 16 preimages $m_1, m_2, ..., m_16$.


The challenge: How to identify the original message $m$ among them?


The walkaround in my mind is to embed a hash at the end of the message so that under the random oracle model, we can distinguish the original message from other preimages with negligible failure. But this seems to be too naive and costly (it reduces the message space by about 80-bit for the hash).


Any thoughts? Thanks!



Footnote: One strawman walkaround is to use hybrid encryption as the elligator paper suggested, such that we no longer need to encode random messages. Yet, this does not work for some applications where we cannot use an elligator, like implementing public-key re-randomizable encryption for shuffling networks.

**Comment by weikengchen** [comment]
Thanks Mike. Very great idea on adding randomness and having a check -- it uses significantly less space. I just feel that it is not constant time, and maybe making it constant time (with negligible failure) can lead to a little bit too slow encoding :)

**Comment by weikengchen** [comment]
For other people looking at this topic.

At least we can reduce the number of hints to try from 32 to 8 by fixing the lowest bit of msg[0] and the highest bit of msg[HASH_BYTE - 1], so you can reduce the number of calls to the inverse elligator.  But for the injective encoding, I haven't yet figure out a provably injective way beyond leaving a hash with the length greater than the security parameter -- there should probably be a better solution since we are merely finding 1 among 8.
